<?php
/**
 * EXAMPLE CONFIGURATION FILE
 *
 * Copy this file to config.php and update with your actual credentials.
 * This file is for local development reference only.
 *
 * Note: In production, config.php is auto-generated by GitHub Actions
 * using secrets stored in the repository settings.
 */

// ========================================
// DATABASE CREDENTIALS
// ========================================
define('DB_HOST', 'localhost');      // Use 'mysql' if running in Docker
define('DB_USER', 'fishing_user');
define('DB_PASS', 'your_password_here');
define('DB_NAME', 'fishing_directory');

// ========================================
// CORS SETTINGS
// ========================================
// In production, use specific domains for security
$allowed_origins = [
    'http://localhost:4321',         // Astro dev server
    'http://localhost:3000',         // Alternative dev port
    'https://yourdomain.com',        // Production domain
    'https://www.yourdomain.com'     // Production www subdomain
];

// ========================================
// RATE LIMITING
// ========================================
// Maximum submissions per hour per IP
define('RATE_LIMIT_SUBMISSIONS', 3);
// Maximum votes per hour per IP
define('RATE_LIMIT_VOTES', 10);

// ========================================
// MAINTENANCE MODE
// ========================================
/**
 * Simple maintenance mode check
 * Create a file named MAINTENANCE in the document root to enable maintenance mode
 * All requests will receive a 503 response
 */

// Check for MAINTENANCE file in document root
$maintenance_file = rtrim($_SERVER['DOCUMENT_ROOT'] ?? __DIR__ . '/..', "\\/") . '/MAINTENANCE';

if (file_exists($maintenance_file)) {
    // Determine if this is an API request or browser request
    $accept = $_SERVER['HTTP_ACCEPT'] ?? '';
    $request_uri = $_SERVER['REQUEST_URI'] ?? '';

    if (strpos($request_uri, '/api/') === 0 || strpos($accept, 'application/json') !== false) {
        // API request - return JSON error
        http_response_code(503);
        header('Content-Type: application/json');
        header('Retry-After: 3600'); // Suggest retry in 1 hour
        echo json_encode([
            'error' => 'Site is temporarily down for maintenance. Please try again later.',
            'maintenance' => true
        ]);
        exit;
    } else {
        // Browser request - show maintenance page
        $htmlPath = rtrim($_SERVER['DOCUMENT_ROOT'] ?? __DIR__ . '/..', "\\/") . '/maintenance.html';
        if (file_exists($htmlPath)) {
            http_response_code(503);
            header('Content-Type: text/html');
            header('Retry-After: 3600');
            echo file_get_contents($htmlPath);
            exit;
        }

        // Fallback if maintenance.html doesn't exist
        http_response_code(503);
        header('Content-Type: text/plain');
        header('Retry-After: 3600');
        echo 'Site is temporarily down for maintenance. Please try again later.';
        exit;
    }
}

// ========================================
// HELPER FUNCTIONS
// ========================================

/**
 * Get database connection
 * @return mysqli
 */
function get_db_connection() {
    $conn = new mysqli(DB_HOST, DB_USER, DB_PASS, DB_NAME);
    if ($conn->connect_error) {
        error_log('Database connection failed: ' . $conn->connect_error);
        http_response_code(500);
        die(json_encode(['error' => 'Database connection failed']));
    }
    $conn->set_charset('utf8mb4');
    return $conn;
}

/**
 * Set CORS headers based on allowed origins
 */
function set_cors_headers() {
    global $allowed_origins;
    $origin = isset($_SERVER['HTTP_ORIGIN']) ? $_SERVER['HTTP_ORIGIN'] : '';

    // In development, be more permissive
    if (in_array($origin, $allowed_origins) || strpos($origin, 'localhost') !== false) {
        header('Access-Control-Allow-Origin: ' . $origin);
    }

    header('Access-Control-Allow-Methods: GET, POST, OPTIONS');
    header('Access-Control-Allow-Headers: Content-Type');
    header('Access-Control-Max-Age: 86400');

    // Handle preflight requests
    if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
        http_response_code(200);
        exit;
    }
}

/**
 * Get hashed IP address for rate limiting (privacy-preserving)
 * Hash includes current hour to reset limits hourly
 * @return string
 */
function get_ip_hash() {
    $ip = $_SERVER['REMOTE_ADDR'] ?? 'unknown';
    // Include hour in hash so it resets every hour
    return hash('sha256', $ip . date('Y-m-d H'));
}

/**
 * Send JSON response and exit
 * @param array $data
 * @param int $status HTTP status code
 */
function send_json($data, $status = 200) {
    http_response_code($status);
    header('Content-Type: application/json');
    echo json_encode($data);
    exit;
}
?>
